name: appcine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_database: ^11.3.7
  flutter:
    sdk: flutter
  youtube_player_flutter: ^9.1.0
  video_player: ^2.8.1
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2
  icons_launcher: ^3.0.1
  chewie: ^1.8.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/imagenes/
    - assets/videos/